name: deploy dev

on:
  push:
    branches: [main]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_GIT_HUB_ACTION_ROLE_ARN }}
          role-session-name: GithubActionsSession

      - name: npm ci
        run: npm ci

      - name: run integration test
        run: npm run test

      - name: deploy to dev
        run: npx sls deploy

      - name: run acceptance tests
        run: npm run acceptance
